author = "Jenny Jones"
baseURL = "https://thephw.com"
copyright = "&copy;2020 Patrick Wiseman"
description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
favicon = "favicon.ico"
languageCode = "en-us"
shareImage = "images/cover1.jpg"
theme = "split"
title = "ThePHWâ„¢"
twitterHandle = "thephw"


[params.visual.image]
  enable = true
  file = "images/cover5.jpg"
  position = "center left"

# Links List #1
[[params.links]]
  [params.links.list1]
    heading = "Social"
    [[params.links.list1.link]]
      text = "ğŸ’Œ Email"
      url = "mailto:me@thephw.com"
    [[params.links.list1.link]]
      text = "ğŸ¦ Twitter"
      url = "https://twitter.com/thephw"
    [[params.links.list1.link]]
      text = "âŒ¨ï¸ Github"
      url = "https://github.com/thephw"
    [[params.links.list1.link]]
      text = "ğŸ‘¨â€ğŸ’¼ LinkedIn"
      url = "https://linkedin.com/in/thephw"
    [[params.links.list1.link]]
      text = "ğŸ“¸ Instagram"
      url = "https://instagram.com/thephw"

  [params.links.list2]
    heading = "Content"
    [[params.links.list2.link]]
      text = "ğŸ“• Articles"
      url = "#"
    [[params.links.list2.link]]
      text = "ğŸ–¥ Code"
      url = "#"
    [[params.links.list2.link]]
      text = "ğŸ‘¨â€ğŸ³ Recipes"
      url = "#"
    [[params.links.list2.link]]
      text = "ğŸª‘ Woodworking"
      url = "#"
    [[params.links.list2.link]]
      text = "ğŸ“· Photos"

  [params.links.list3]
    heading = "Good Company"
    [[params.links.list3.link]]
      text = "ğŸš€ Spaceship"
      url = "https://spaceship.run"
    [[params.links.list3.link]]
      text = "ğŸ’¼ Deft Services"
      url = "https://deft.services"
    [[params.links.list3.link]]
      text = "ğŸ• Rails Camp South"
      url = "https//us-south.rails.camp"
